/*
  This file is generated by SpeakUp Software. It containts voice commands constants.
  Creation date: 04/01/2016
  Creation time: 14:22:38
*/


/*
  Name: 0
  Index: 0
  Length: 1.0 s
  Description: attiva attenzione per i comandi successivi
*/
const VCMD_0 = 0;

/*
  Name: 1
  Index: 1
  Length: 1.0 s
  Description: 
*/
const VCMD_1 = 1;

/*
  Name: 2
  Index: 2
  Length: 1.0 s
  Description: 
*/
const VCMD_2 = 2;

/*
  Name: 3
  Index: 3
  Length: 1.0 s
  Description: 
*/
const VCMD_3 = 3;

/*
  Name: 4
  Index: 4
  Length: 1.0 s
  Description: 
*/
const VCMD_4 = 4;

/*
  Name: 5
  Index: 5
  Length: 1.0 s
  Description: 
*/
const VCMD_5 = 5;

/*
  Name: 6
  Index: 6
  Length: 1.0 s
  Description: 
*/
const VCMD_6 = 6;

/*
  Name: 7
  Index: 7
  Length: 1.0 s
  Description: 
*/
const VCMD_7 = 7;

/*
  Name: 8
  Index: 8
  Length: 1.0 s
  Description: 
*/
const VCMD_8 = 8;

/*
  Name: 9
  Index: 9
  Length: 1.0 s
  Description: 
*/
const VCMD_9 = 9;

/*
  Name: ok
  Index: 10
  Length: 1.0 s
  Description: 
*/
const VCMD_OK = 10;

/*
  Name: avanti
  Index: 11
  Length: 1.0 s
  Description: 
*/
const VCMD_AVANTI = 11;

/*
  Name: indietro
  Index: 12
  Length: 1.0 s
  Description: 
*/
const VCMD_INDIETRO = 12;

/*
  Name: destra
  Index: 13
  Length: 1.0 s
  Description: 
*/
const VCMD_DESTRA = 13;

/*
  Name: sinistra
  Index: 14
  Length: 1.0 s
  Description: 
*/
const VCMD_SINISTRA = 14;

/*
  Name: ferma
  Index: 15
  Length: 1.0 s
  Description: 
*/
const VCMD_FERMA = 15;

/*
  Name: no
  Index: 16
  Length: 1.0 s
  Description: 
*/
const VCMD_NO = 16;

/*
  Name: vai
  Index: 17
  Length: 1.0 s
  Description: 
*/
const VCMD_VAI = 17;

/*
  Name: sala
  Index: 18
  Length: 1.0 s
  Description: 
*/
const VCMD_SALA = 18;

/*
  Name: ingresso
  Index: 19
  Length: 1.0 s
  Description: 
*/
const VCMD_INGRESSO = 19;

/*
  Name: cucina
  Index: 20
  Length: 1.0 s
  Description: 
*/
const VCMD_CUCINA = 20;

/*
  Name: corridoio
  Index: 21
  Length: 1.0 s
  Description: 
*/
const VCMD_CORRIDOIO = 21;

/*
  Name: camera
  Index: 22
  Length: 1.0 s
  Description: 
*/
const VCMD_CAMERA = 22;

/*
  Name: studio
  Index: 23
  Length: 1.0 s
  Description: 
*/
const VCMD_STUDIO = 23;

/*
  Name: cameretta
  Index: 24
  Length: 1.0 s
  Description: 
*/
const VCMD_CAMERETTA = 24;


